### ISSUE TITLE
Thesis English version

### ISSUE THREAD

**Issue by mrka124** [jdhao/master_thesis#1]
Do you have English version of your thesis? I have same problem with you. My dataset contain many image with different size, many orientation,.. like firearm. 

Also I'm using Pytorch with batch size = 1 (I have SPP layer in network), forward one image at time. So my training time is very slow. Do you have any suggestion?

Sorry for my bad English.

**Comment by jdhao** [comment]
Sorry, this thesis is written only in Chinese.  The related part about firearm is published as a conference paper at ICPR 2018. You can find it [here](https://arxiv.org/abs/1806.02984).

To speed training, you can try to reduce the image size, which is very important. You can also forward multiple images and do one backward. You may find the code [here](https://github.com/jdhao/deep_firearm) helpful. Specifically, you can check the code in the source file `train_retr_from_cls.py`.

**Comment by mrka124** [comment]
Thank you!!!
